import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full py-6 bg-black/80 backdrop-blur-md border-b border-zinc-800">
          <nav className="flex justify-center gap-12">
            <a href="#hero" className="text-zinc-50 text-lg font-semibold hover:text-zinc-400 transition">Accueil</a>
            <a href="#biographie" className="text-zinc-50 text-lg font-semibold hover:text-zinc-400 transition">Biographie</a>
            <a href="#discographie" className="text-zinc-50 text-lg font-semibold hover:text-zinc-400 transition">Discographie</a>
            <a href="#galerie" className="text-zinc-50 text-lg font-semibold hover:text-zinc-400 transition">Galerie</a>
            <a href="#contact" className="text-zinc-50 text-lg font-semibold hover:text-zinc-400 transition">Contact</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
